### PR TITLE
Adding support for multiple processes

### LINKED ISSUE #103: Puppet always execute start for program with numprocs != 1
Status check for single process works okay. But for homogeneous group `systemctl status program` returns "No such process" because correct syntax is `systemctl status program:XX`. So, the check always fails and puppet always reapplying start command.

### PR DESCRIPTION
**Pull request by wardhus**
This fixes #103

### CODE REVIEW

**Comment by netdata** [comment]
Hi @wardhus Thanks for fixing this
@ajcrowe can you have a look at this?

**Comment by ajcrowe** [comment]
This looks good @wardhus, can you fix the build and I will merge this

**Comment by mwalton236** [comment]
Do the tests just need re-run? Looks like the build failure is unrelated to the changes in this PR.

**Comment by jacobmw** [comment]
Looks like it would be an easy enough fix to get this build to work.  Realizing it's not a file you touched but was probably present when you forked the module.  Want to just try it so that @ajcrowe  can merge this in.  I'd love to have puppet stop trying to restart my supervisor programs on every run.

**Comment by Misho-98118** [comment]
Hi. Has anybody applied this fix successfully. I hit similar issue and can't make it run properly even with the proposed fix. Any advice is appreciated.

**Comment by wardhus** [comment]
We've been running my fork in production ever since I made this pull request. You can do the same until this gets merged. :)

**Comment by Misho-98118** [comment]
Hi @wardhus, thank you for the clarification. On second try, I made it works. 
Hey, @ajcrowe, I think this is important fix and would be nice to be in master.

**Comment by jacobmw** [comment]
I'd really like to see this get merged into master as we continue to see puppet attempting to restart services on every run.

**Comment by ajcrowe** [comment]
Sorry it took so long to get this merged!

**Pull request merged**
